spring.application.name=backend
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/retrofit
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=UnaClaveSuperSeguraDeAlMenos256Bits1234567890
jwt.expiration=3600000

spring.servlet.multipart.max-file-size=15MB

spring.servlet.multipart.max-request-size=50MB